### PR TITLE
code changes for Ruboto compatibility...

### PR DESCRIPTION
**Pull request by gfowley**
readline raises Argument error: add to rescues
require irb raises Argument error (readline again): wrap irb.rb to rescue
Processor.print_location_and_text calls Kernel.print sending output to application stdout: make print_location_and_text an instance method so print will call Interface#print and send output to debugger client
linecache-1.3.1 updated for Ruboto compatibility: update gem dependency

### CODE REVIEW

**Comment by gfowley** [comment]
Preserved ChangeLogs as requested.

**Comment by os97673** [comment]
AM I right that IRB command just should not be available on Android with jruby?
BTW what is the actual exception is thrown?  Perhaps it should be reported to jruby team?

**Comment by gfowley** [comment]
Thanks for looking into this.

That is correct, the IRB command should not be available in JRuby on Android.

The actual exception is:
```
org.jruby.embed.EvalFailedException: (ArgumentError) Java package `org.jruby.ext.readline.ReadlineService.new' does not have a method `load'            
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:132)                                                                   
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1353)                                                                     
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1346)                                                                
        at java.lang.reflect.Method.invokeNative(Native Method)                                                                                         
        at java.lang.reflect.Method.invoke(Method.java:515)                                                                                             
        at org.ruboto.JRubyAdapter.runScriptlet(JRubyAdapter.java:104)                                                                                  
        at org.ruboto.ScriptLoader$1.run(ScriptLoader.java:79)                                                                                          
        at java.lang.Thread.run(Thread.java:841)                                                                                                        
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) Java package `org.jruby.ext.readline.ReadlineService.new' does not have a method `load' 
        at RUBY.method_missing(file:/data/app/net.iqeo.debugging-1.apk!/jruby/java/java_package_module_template.rb:13)                                  
        at RUBY.(root)(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/readline.rb:11)                                                   
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)                                                                                 
        at RUBY.(root)(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)                            
        at RUBY.require(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)                          
        at RUBY.LocalInterface(file:/data/app/net.iqeo.debugging-1.apk!/ruby-debug/interface.rb:113)                                                    
        at RUBY.Debugger(file:/data/app/net.iqeo.debugging-1.apk!/ruby-debug/interface.rb:53)                                                           
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)                                                                                 
        at RUBY.(root)(file:/data/app/net.iqeo.debugging-1.apk!/ruby-debug/interface.rb:1)                                                              
        at RUBY.(root)(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)                            
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)                                                                                 
        at RUBY.require(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)                          
        at RUBY.(root)(file:/data/app/net.iqeo.debugging-1.apk!/ruby-debug/processor.rb:1)                                                              
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)                                                                                 
        at RUBY.(root)(/data/app/net.iqeo.debugging-1.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)                            
```

Parts of JRuby that are not supported on Android are removed when packaged by Ruboto with an Android app. This looks like an error caused by the missing class - ```org.jruby.ext.readline.ReadlineService.new``` is misinterpreted as a Java package ?
Repackaging JRuby for Android has resisted my attempts to solve this - the rabbit hole just gets deeper. 

My understanding is that with JRuby 9000 released, the JRuby 1.7.xx series is in compatibility/maintenance mode. Work is in progress in Ruboto to adopt JRuby 9000, but until then a problem like this is an orphan.

**Comment by os97673** [comment]
thank you for the contribution.  Need to figure out how to release a new version of ruby-debug for jruby ;)

**Comment by gfowley** [comment]
Thanks for accepting.

I'd be happy to build the gem(s), only ruby-debug-base needs a java platform gem, ruby-debug is good as a ruby platform gem. Let me know version, etc..

**Comment by os97673** [comment]
well, the version will be 0.10.6.  The only problem is that cli tests are hanging :(  I've never released this gem so it will take some time to figure out what is wrong.

**Comment by os97673** [comment]
I do not use ruby-debug (ruby-debug-base only) could you please try to build the gem and play with it, if it works let me know and I will release it.

**Comment by gfowley** [comment]
Sure, I'll look into it, it'll be a few days.

**Comment by gfowley** [comment]
For MRI Ruby 1.8.7 : all tests pass.
For JRuby 1.7.22 in 1.9 (default) mode : test:base passes, test:cli hangs,
For JRuby 1.7.22 in 1.8 mode : test:base passes, test:cli hangs.

Going back to pre-PR commit ```3352120 time to release 0.10.6``` I get the same test results for MRI and JRuby.

Playing with the gems created under JRuby and using ```rdebug```, all seems fine. But I'd feel better about it if I can get the cli tests working under JRuby. I'll have a look at that in a few days.

**Comment by os97673** [comment]
> I'll have a look at that in a few days.

thank you.  I might be off-line for about a week (so do not expect imidiate response) but I will be back after that ;)

**Pull request merged**
